import React from 'react';
import './styleHistoria.css';

const HistoriaOriginal = () => {
  return (
    <div className="historia-container">
      <h1>Historia Completa de Star Wars</h1>

      <section className="epoca">
        <h2>Amanecer de los Jedi (~25,000 ABY)</h2>
        <img src="public/img/Historia/1.jpg" alt="Amanecer Jedi" />
        <p>Star Wars: Amanecer de los Jedi (Star Wars: Dawn of the Jedi, en inglés) es una serie de cómics publicada por la editorial Dark Horse Comics, escrita por John Ostrander y dibujada por Jan Duursema,el equipo creativo tras la aclamada serie de la misma editorial titulada Star Wars: Legado (Star Wars: Legacy, en inglés). La trama comienza casi 26.000 años antes de Star Wars IV Una Nueva Esperanza, y se centra en la Orden Je'daii, un grupo de individuos sensibles a la Fuerza establecidos en el planeta Tython y predecesores de los Jedi, en tiempos previos a la polarización entre los lados Luminoso y Oscuro de la Fuerza. Es la primera serie situada antes de la fundación de la República Galáctica, en la era llamada "Antes de la República" o "Era Pre-República".

El 1 de febrero de 2012 se publicó un "Número 0" como introducción a la serie, seguido del primer número regular el día 15 del mismo mes. Se publicaron quince números de forma regular aunque no mensual, divididos entre tres arcos argumentales: Tormenta de Fuerza, Prisionero de Bogan y La Guerra de la Fuerza. Tras una breve introducción situada en el año 36.453 ABY, casi toda la acción transcurre durante el año 25.793 ABY. La tama se centra en torno a tres Viajeros Je'daii : Shae Koda, Tasha Ryo y Sek'nos Rath, así como Xesh, un Sabueso de la Fuerza del Imperio Infinito Rakata, y gira en torno a los planes del Je'daii loco Daegen Lok para derrocar a la Orden Je'daii y el posterior intento de los Rakata de conquistar el Sistema Tython. Amanecer de los Jedi terminó tras su tercer arco argumental, debido a la adquisición de la licencia de los cómics de Star Wars por parte de Marvel Comics en 2015 y dejando numerosos interrogantes acerca de los Je'daii en el aire. La publicación en España corrió a cargo de la editorial Planeta DeAgostini en tres recopilatorios en rústica.</p>
      </section>

      <section className="epoca">
        <h2>La Alta República (300–82 ABY)</h2>
        <img src="public/img/Historia/2.jpg" alt="Alta República" />
        <p>«En los días de la Alta República, la galaxia no estaba tan poblada como ahora. Áreas como el Borde Exterior eran peligrosas, difíciles de navegar. Así que la gente de esa época construyó una enorme estación espacial con gran esfuerzo y gasto y la colocó en el centro de las zonas oscuras. Enviaba una señal que actuaba como una especie de baliza, ayudando a los viajeros a encontrar su camino. Le dieron a esa estación un nombre inspirador que se ajustaba a su propósito.»
―Comandante Grek[fuente]
De acuerdo las historias contadas entre los Iniciados Jedi, Klias Teradine era un padawan que vivió durante esta era y también descubrió la Colección Bogan.[9] Un acontecimiento conocido como el Gran Desastre Hiperespacial, en el que naves estelares a través de la galaxia fueron repentinamente expulsadas del hiperespacio, también ocurrió durante esta era.[6]

Durante este tiempo, la galaxia no estaba tan poblada como en la época de la Guerra Civil Galáctica, ya que áreas como el Borde Exterior eran peligrosas y difíciles de navegar. En respuesta, una enorme estación espacial llamada Faro Starlight, una de las Grandes Obras de la Canciller Suprema Lina Soh, fue construida con un gran esfuerzo y gasto y colocada en el centro de las zonas oscuras. La estación enviaría una señal que actuaba como un faro, ayudando a los viajeros a encontrar su camino.[5]

Se sabía que los clanes Starros y San Tekka estaban activos durante este período. El Maestro Jedi Porter Engle, conocido como la Espada de Bardotta, también data de este periodo.[10] Avar Kriss fue una destacada Maestra Jedi de la época, que llegó a ser conocida como la «Heroína de Hetzal» por sus esfuerzos por liderar a un grupo de Jedi para rescatar a civiles durante el Gran Desastre Hiperespacial.[11] Pronto se descubrió que el grupo de merodeadores conocido como los nihil era el responsable de la tragedia.[12]

Mucho después de la era de la Alta República, el Maestro Jedi Luke Skywalker y el explorador galáctico Lor San Tekka viajaron a un puesto de avanzada Jedi en el planeta Elphrona del Borde Exterior, ubicado en el borde de las Regiones Desconocidas. Dada su distancia del Núcleo, Tekka especuló que el puesto de avanzada podría haber sido construido durante la era de la Alta República.[3]</p>
      </section>

      <section className="epoca">
        <h2>Caída de los Jedi (82–19 ABY)</h2>
        <img src="public/img/Historia/3.jpg" alt="Caída Jedi" />
        <p>La Gran Purga Jedi (19 ABY—), también conocida como la guerra contra los Jedi, fue el periodo en el que la Orden Jedi fue destruida por los Sith, y los Jedi fueron cazados hasta la casi extinción por el Imperio Galáctico. La caída de los Jedi tiene sus orígenes en las guerras ancestrales que estos libraron con los Sith, al final de las cuales estos últimos serian casi por los Jedi. Desde entonces, los Sith operaron en secreto, planeando la eventual destrucción de la Orden Jedi. Un milenio mas tarde, Darth Sidious, bajo su identidad publica de senador y más tarde del Canciller Supremo Palpatine, manipuló a la galaxia sumiéndola en las Guerras Clon como pretexto para ganar poderes ejecutivos de emergencia sobre la República Galáctica. Él usó la guerra para manipular al Senado de darle virtualmente más poderes ejecutivos en nombre de la seguridad. Además, al ejército clon que proveyó a la República con su fuerza militar, se le habían sido implantados biochips por sus creadores Sith, que, al activarse, activarían una fuerza y disposición total de los clones para matar a sus líderes Jedi.

La Purga Jedi inició al final de las Guerras Clon. Anakin Skywalker, un Caballero Jedi de quien se creía que era el Elegido destinado a destruir a los Sith, descubrió que Palpatine era Darth Sidious y le informó al Maestro Jedi Mace Windu. En lo que Palpatine calificaría públicamente como la «rebelión Jedi», Windu y otros tres Maestros Jedi confrontaron al Canciller, quien mató a los tres maestros y enfrento a Windu en un duelo de sables de luz. Skywalker, quien buscaba el poder de Sidious para salvar a su esposa, Padmé Amidala, de la muerte, intervino e incapacitó a Windu antes de que este pudiera acabar con el Señor Oscuro. Sidious mató a Windu y Anakin se convirtió en el Lord Sith Darth Vader, liderando la Operación: Caída del Caballero y matando a todos dentro. Mientras Vader ejecutaba el asalto en el Templo, Sidious inició la Orden 66, con esta última causando que los biochips de los clones les lavaran el cerebro para masacrar a los Jedi, llevando finalmente a que la Orden Jedi fuera casi destruida. Con los Jedi tachados de traidores y las Guerras Clon llegadas a su fin, Sidious se declaró a sí mismo emperador y restauró el Imperio Sith cuando transformó a la República en el Imperio Galáctico. Sin embargo, un pequeño número de Jedi que o no se vieron envueltos con clones o escaparon de la trampa, sobrevivieron y continuaron fastidiando a los Sith en años posteriores.

La Era del Imperio vio la eliminación sistemática de los Jedi sobrevivientes por el Imperio. Vader comandó a un número de Inquisidores, cuyo trabajo era darle caza a todo Jedi sobreviviente. El Gran Inquisidor, un antiguo Guardia del Templo Jedi proveniente de Utapau, persiguió a un grupo de rebeldes en el planeta Lothal entre los que estaba un antiguo padawan, Kanan Jarrus. Estos rebeldes últimamente ayudarían a crear la Alianza para Restaurar la República, la cual lucharía contra el Imperio durante la Guerra Civil Galáctica. Uno de estos rebeldes era el hijo de Vader, Luke Skywalker, quien se convirtió en el último de los Jedi y ayudó a guiar a su padre a redimirse. Vader murió poco después de que él asesinara a Sidious para salvar a su hijo, trayendo un final al dominio Sith sobre la galaxia.</p>
      </section>

      <section className="epoca">
        <h2>Reinado del Imperio (19–0 ABY)</h2>
        <img src="public/img/Historia/4.jpg" alt="Imperio Galáctico" />
        <p>El Imperio Galáctico, y más tarde recordado como El Viejo Imperio, fue el gobierno galáctico y autocrático que procesó un imperio de galaxias que reemplazó a la República Galáctica en las secuelas de las Guerras Clon.

Alcanzando el poder en los últimos años de la República, el Lord Sith Darth Sidious aseguró gradualmente el gobierno bajo su control a través de Sheev Palpatine, el último Canciller Supremo de la República. A través de sus maquinaciones como Sidious y Palpatine, los Sith fueron restaurados a una posición de dominio en medio de la caída de la Orden Jedi y la marginación del Senado Galáctico. Sin los guardianes Jedi de paz y justicia para oponerse a él, Sidious puso fin a mil años de democracia; en su lugar instaló la regla absoluta de sí mismo como Emperador Galáctico.

Durante más de dos décadas, la oposición al régimen imperial fue reprimida implacablemente por las fuerzas armadas en rápido crecimiento del Imperio. Durante la mayor parte de la existencia del Imperio, el Senado Imperial permaneció dentro del Imperio como el último símbolo sobreviviente de la República. Con la finalización de la Estrella de la Muerte, el Emperador se sintió lo suficientemente seguro para disolver el cuerpo de representantes galácticos mientras mantenía su control sobre la galaxia a través de un colectivo de gobernadores del sector y el temor general que inspiraría la nueva estación de batalla. Sin embargo, el creciente resentimiento hacia el gobierno Imperial condujo gradualmente al surgimiento de varios movimientos de resistencia que finalmente culminaron en la formación de la Alianza para Restaurar la República. Unidos por un objetivo común, la Alianza se convirtió en una amenaza viable para el Imperio después de su exitoso robo de los planos de la Estrella de la Muerte y la subsiguiente destrucción de la estación en la Batalla de Yavin.

A lo largo de la Guerra Civil Galáctica, las fuerzas imperiales y de la Alianza lucharon en toda la galaxia en un conflicto que culminó con la muerte de Darth Sidious y su aprendiz, Darth Vader, en la Batalla de Endor en el 4 DBY. Con la extinción Sith, el Gran Visir del Consejo Imperial Regente, Mas Amedda, sucedió efectivamente a Palpatine como Emperador en todo menos en el nombre, pero tuvo un poder limitado más allá de Coruscant mientras el Imperio evolucionó completamente en una estratocracia dominada por oficiales militares. Fue durante este tiempo cuando el Imperio se dividió en una variedad de facciones separadas, feudos y remanentes, conocidos como Remanentes Imperiales, dominados por varios señores de la guerra, moffs disidentes, gobernadores, almirantes y generales debido a la falta de una línea de sucesión para el trono imperial y la cadena de mando poco clara mientras el gobierno imperial oficial permanecía en Coruscant. Sin embargo, cuando las fuerzas destrozadas del Imperio lucharon por mantener su esfuerzo de guerra contra el creciente impulso de la recién formada Nueva República, el poder de Amedda y el gobierno centralizado se desvaneció con el ascenso del Almirante de Flota Gallius Rax, un caudillo que controlaba la mayor fracción de la Armada Imperial.

Un año después del fallecimiento de Palpatine, Rax, que controlaba la flota imperial más grande y ocupaba el puesto de Consejero del Imperio, organizó el Remanente Imperial de Jakku mientras el Imperio tomaba su posición final en el mundo desértico de Jakku en la Batalla de Jakku contra el Nuevo República. Sin embargo, el Consejero Rax murió y el Imperio fue derrotado decisivamente por la República, consecuentemente resultando en su capitulación a la República a través de la firma del Concordato Galáctico en el 5 DBY que condujo a la disolución del gobierno imperial central, reduciendo el Imperio a un resto del estado que una vez fue. Durante la era de la Nueva República, lo que quedaba del Imperio se descentralizó y se transformó en un mosaico de posesiones territoriales independientes, todas políticamente unidas por la tradición y los ideales imperiales, aunque encerradas en estrictos tratados de desarme y duras reparaciones. Una de estas entidades se formó en Core and Inner Rim, que se vio obligada a permanecer dentro de sus fronteras. Un nuevo gobierno en Coruscant, dirigido por el Gran Visir Mas Amedda y supervisado por la República, se formó, aunque era una administración provincial que tenía poco poder real.

Sin embargo, a pesar de la caída del Imperio, su legado perduró durante décadas en las Regiones Desconocidas del espacio, donde antiguos oficiales imperiales, nobles, tecnólogos, soldados y leales, entre ellos la Gran Almirante Rae Sloane y el Comandante Brendol Hux, habían abandonado la nave para después la Batalla de Jakku a través de los esfuerzos de Rax y una Contingencia secreta ideada por Darth Sidious basada en el conocimiento proporcionado por el Gran Almirante Thrawn, nativo de las Regiones Desconocidas. Allí, formaron una junta militar llamada la Primera Orden, y comenzaron a construir sus fuerzas militares en secreto y tramando su eventual regreso al poder y la recuperación del legado y la causa perdidos del Imperio.</p>
      </section>

<section className="epoca">
        <h2>Era de la Rebelión (0–5 DBY)</h2>
        <img src="public/img/Historia/5.jpg" alt="Rebelión" />
        <p>La Era de la Rebelión esta marcada principalmente por el opresivo gobierno del Imperio Galáctico y la incansable lucha de la Alianza Rebelde para restaurar la justicia en la Galaxia a lo largo de la Guerra Civil Galáctica. En este periodo se destaca la incorporación de Luke Skywalker y Han Solo a la Rebelión junto con Leia Organa, el entrenamiento Jedi de Luke bajo las enseñanzas de Obi Wan Kenobi y Yoda y las grandes batallas de la guerra como la de Yavin, Hoth y Endor hasta la caída del Imperio.</p>
      </section>

      <section className="epoca">
        <h2>La Nueva República (5–28 DBY)</h2>
        <img src="public/img/Historia/6.jpg" alt="Nueva República" />
        <p>La Nueva República (NR), también conocida como simplemente como la República, la Alianza o la Rebelión, fue el gobierno democrático galáctico formado a partir de las cenizas del conflicto durante los últimos años de la Guerra Civil Galáctica, absorbiendo el liderazgo político y militar de la antigua Alianza para Restaurar la República después de la Batalla de Endor en el 4 DBY. La Nueva República siguió los pasos de la República Galáctica, comúnmente conocida en ese momento como la "Antigua República" durante la Era del Imperio, restaurando el Senado Galáctico y luchando contra las destrozadas fuerzas del Imperio Galáctico. A diferencia de su predecesora, la capital de la Nueva República no estaba en Coruscant, y después de un breve periodo en Chandrila, estableció su capital en una variedad de mundos miembros en forma rotativa, elegida mediante elección democrática.

Una fracción del tamaño de la antigua República Galáctica y el Imperio, la Nueva República mantuvo términos amistosos con la mayoría de los sistemas galácticos debido a los procesos igualitarios que incorporó en su mensaje político. Brevemente, la Primera Orden se separaría finalmente del mayor cuerpo una vez que las relaciones tensas alcanzaron un punto de ruptura. Mientras que muchos aplaudieron la propuesta, otros se dieron cuenta de que sin la supervisión de la República, la Primera Orden regresaría a las draconianas formas de su predecesor. Con un hambre de paz a través de la galaxia, muchos senadores—algunos recibiendo grandes sumas de créditos de sus beneficiarios de la Primera Orden—rechazaron la noción de que la Primera Orden sería una amenaza para la República, creyendo que los informes de su fuerza fueron exagerados por la 'belicista' Leia Organa y su Resistencia. Tras las verdaderas intenciones definitivamente reveladas después de la destrucción de la capital de la República en el sistema Hosnian, la República estaba al borde de otra guerra galáctica.</p>
      </section>

      <section className="epoca">
        <h2>Ascenso de la Primera Orden (28–35 DBY)</h2>
        <img src="public/img/Historia/7.jpg" alt="Primera Orden" />
        <p>La Primera Orden, o también conocida como la Orden, era una facción política y militar gobernada por el Líder Supremo Snoke, pronto asumida por Kylo Ren y aliado con los Caballeros de Ren, que surgió como resultado de la caída del Imperio Galáctico. Después de la Batalla de Jakku, el Imperio se rindió formalmente ante la Nueva República al firmar el Concordato Galáctico, un tratado de paz que marcó el final de la Guerra Civil Galáctica en el 5 DBY. A pesar de su colapso, el legado del Imperio sobrevivió en las Regiones Desconocidas de la galaxia, donde los ex miembros de las Fuerzas Armadas Imperiales tramaron su regreso al poder. Su causa crecería en apoyo a través de algunos simpatizantes imperiales que brevemente habitaron un ala de la política de la República antes de abandonar la naciente democracia para unirse al movimiento imperial en las Regiones Desconocidas. Inspirado por los ideales fascistas del Imperio, este movimiento buscó ser mejor y eliminar todas las debilidades y defectos que tenía el Imperio, lo que finalmente resultó en la formación de la Primera Orden.

En las décadas que siguieron a la derrota del Imperio, la Primera Orden gradualmente construyó su fuerza a través de la movilización secreta de nuevas flotas y ejércitos en violación del Concordato Galáctico y la ley de la República. A pesar de nuevos actos de desafío al tratado, el Senado Galáctico no consideró la Primera Orden como una amenaza real para la República. Sin embargo, la inacción del Senado motivó a la veterana rebelde, Leia Organa, a fundar la Resistencia. Aunque la Primera Orden se enredó en un conflicto con el grupo de Organa, la República siguió siendo su objetivo principal. Después de treinta años de planear su venganza contra el gobierno que derrocó al Imperio, la Primera Orden puso a prueba la superarma de la Base Starkiller en el Sistema Hosnian destruyendo Hosnian Prime, el mundo capital de la República. Poco después, la Resistencia lanzó un contraataque que resultó en la destrucción de su base.</p>
      </section>
    </div>
  );
};

export default HistoriaOriginal;
